baseurl: "/"
title: "universal"
main_js: "assets/js/main.js"
params:
  palette: blue
  palettes:
    blue:
      sass:
        accent: "#3eb2fd"
    green:
      sass:
        accent: "#31fd9c"
menus:
  main:
    - identifier: submenu
      title: Submenu
      weight: 3
      url: "#"
  submenu:
    - identifier: option1
      title: Option One
      weight: 1
      url: "#"
    - identifier: option2
      title: Option Two
      weight: 2
      url: "#"
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
